github:
  client:
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user
google:
  client:
    accessTokenUri: https://accounts.google.com/o/oauth2/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: form
    scope: ['openid', 'email']
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
facebook:
  client:
    accessTokenUri: https://graph.facebook.com/v3.2/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: ['public_profile']
  resource:
    userInfoUri: https://graph.facebook.com/me
spring:
  resources:
    chain:
      enabled: true
server.session.timeout: 3600
server.port: 8000
multipart.maxFileSize: 25Mb
multipart.maxRequestSize: 25Mb
